### ISSUE TITLE
Failing to connect to mosquitto MQTT server

### ISSUE THREAD

**Issue by Aphris-Karu** [Juerd/Net-MQTT-Simple#10]
For some reason when my perl script tries to connect to the mosquitto MQTT server it gets a socket error.

1568058091: New client connected from 10.0.10.13 as Net::MQTT::Simple[JWDZKXAWLM] (p2, c1, k60).
1568058091: Socket error on client Net::MQTT::Simple[JWDZKXAWLM], disconnecting.

This was working several months ago but seems to be broken now.

**Comment by Juerd** [comment]
Aphris-Karu skribis 2019-09-09 12:44 (-0700):
> 1568058091: New client connected from 10.0.10.13 as Net::MQTT::Simple[JWDZKXAWLM] (p2, c1, k60).
> 1568058091: Socket error on client Net::MQTT::Simple[JWDZKXAWLM], disconnecting.
> This was working several months ago but seems to be broken now.

Which version of Net::MQTT::Simple are you using?

This looks like a bug that is fixed in recent editions.

**Comment by Aphris-Karu** [comment]
It's v1.24 

It is talking to an insecure mqtt server in a docker swarm. I found that if I add a login line with just the login and no password it fixed the problem.
