### ISSUE TITLE
Rapid Publish produces Mosquitto socket error / disconnect

### ISSUE THREAD

**Issue by christianTF** [Juerd/Net-MQTT-Simple#11]
Hello Juerd,

today I stumbled over an issue with fast publishing.
In case of publishing multiple messages in a loop, only few messages arrive (1 to 3), then Mosquitto disconnects.

**MQTT arrival**
![image](https://user-images.githubusercontent.com/14220265/75831065-d0fc9f00-5db2-11ea-9103-255f3a018ec2.png)

**Mosquitto Log**
![image](https://user-images.githubusercontent.com/14220265/75830963-87ac4f80-5db2-11ea-8069-ac529a8fa4dd.png)

To reproduce the issue, I've created this simple script:

```perl
use Net::MQTT::Simple;
print "Version: " . $Net::MQTT::Simple::VERSION . "\n"; 

my $basetopic = "test/";
my $content = 'aaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccddddddddddddddddddd';

$ENV{MQTT_SIMPLE_ALLOW_INSECURE_LOGIN} = 1; 
my $mqtt = Net::MQTT::Simple->new('localhost:1883');
$mqtt->login('loxberry', 'loxberry');

for my $a ( 1..10 ) {
	print "Number $a\n";
	$mqtt->publish( $basetopic.$a, $content );
}

$mqtt->disconnect();
```

**Output is:**
![image](https://user-images.githubusercontent.com/14220265/75831545-0b1a7080-5db4-11ea-9e19-437f770d60d1.png)

If I implement a `Time::HiRes::sleep(0.01)`, the submission is ok and no socket error. Maybe the stream gets overwritten. 

Environment is a Raspberry Pi 2B with Debian 10 Buster. 
Mosquitto is 1.5.7
I've updated to your latest master before of the test.

I would be happy if you could take a look, or could give me feedback, that this might be a Raspberry timing issue not appearing on a PC.

Thanks!
Christian

**Comment by Sloth-on-meth** [comment]
hi, same issue here! where do you implement the time::hires::sleep? can you submit a PR?

**Comment by Juerd** [comment]
Hi, thanks for filing an issue.

I've not been able to reproduce this problem, and think it might be on the server side.
