### ISSUE TITLE
Provide an example of how to receive only one retained message

### ISSUE THREAD

**Issue by dmak** [Juerd/Net-MQTT-Simple#17]
I wonder how to implement the following functionality:
```
mosquitto_sub -C 1 -t ...
```
i.e. read one (retained) message from the topic.

The following code does not wait for 5 seconds and also does not receive any message from the topic (prints `Tick: 1` to the console):
```
my $mqtt = Net::MQTT::Simple->new(MQTT_HOST);
$mqtt->login($mqtt_user, $mqtt_pass);
$mqtt->subscribe(MQTT_TOPIC, sub {
	shift;
	print "Received the message: " . shift . "\n";
});
print "Tick: " . $mqtt->tick(5) . "\n";
$mqtt->disconnect();
```
Thanks in advance!

**Comment by dmak** [comment]
Thanks. The utility calls [`run()`](https://metacpan.org/dist/Net-MQTT-Simple/source/bin/mqtt-simple#L120) function which I cannot afford as it enters the endless loop and calls `exit()` to abort the program from message handler.
I need exactly the logic I've described: receive the message from the topic and then the program flow continues. If there is no message send by the server, then wait some time and continue:
```
my $message = undef;
$mqtt->subscribe(MQTT_TOPIC, sub {
	shift;
	$message = shift;
});
# ... some long-running initialization ...
if (!$message) {
	$mqtt->tick(5); # give one more chance to receive the message
	if (!$message) {
		$mqtt->unsubscribe(MQTT_TOPIC);
		$message = { 'default' => 'value' };
	}
}
# ... the program continues either with received message or with default values ...
```

**Comment by Juerd** [comment]
I believe the new functionality introduced in v1.30 provides the requested feature.
