### ISSUE TITLE
Client <clientname> disconnected due to malformed packet.

### ISSUE THREAD

**Issue by CRCinAU** [Juerd/Net-MQTT-Simple#18]
Firstly, thanks for the module - its come in very handy.

I'm trying to send a binary JPG in a publish, but it seems like after about 16Kb (at a guess), mosquitto will disconnect the client with the error:
```
Client <clientname> disconnected due to malformed packet.
```

It also seems like the last kb or so of the JPG is corrupted - ie the file doesn't display properly.

If I scale the JPG down to ~6Kb, then things seem to send fine - although I can only seem to manage a 203x152 resolution JPG at that point.

Is there something magical around the 16Kb boundary? I note that's what is set as:
```
our $READ_BYTES = 16 * 1024;  # 16 kB per IO::Socket::SSL recommendation
```

This connection is via Net::MQTT::Simple::SSL - and sending over a WAN link.

**Comment by Juerd** [comment]
Steven Haigh skribis 2022-09-02  4:22 (-0700):
>I'm trying to send a binary JPG in a publish, but it seems like after about 16Kb (at a guess), mosquitto will disconnect the client with the error:
> (...)
>Is there something magical around the 16Kb boundary? I note that's what is set as:
>```
>our $READ_BYTES = 16 * 1024;  # 16 kB per IO::Socket::SSL recommendation
>```
>This connection is via Net::MQTT::Simple::SSL - and sending over a WAN link.

There is; 16 kB is the maximum size of an SSL frame. IO::Socket::SSL says that using syswrite, only 16 kB will be written at a time. I had interpreted that as that it would chunk the data for you, but apparently it means you have to call it multiple times yourself.

I have no time to try it now, but maybe you could try changing lines 195 and 196 of Simple.pm to:

     while (my $chunk = substr $data, 0, 16384, "") {
         syswrite $socket, $data
             or $self->_drop_connection;  # reconnect on next message
     }

Maybe even lower the 16384 if this doesn't work; I don't know if there's any overhead in SSL frames that must be accounted for.

**Comment by CRCinAU** [comment]
Ok, I'll put this on my list for next week... We currently install via CPAN in a Dockerfile - so I'll look at applying a patch or similar after the install.

**Comment by CRCinAU** [comment]
I tried the code change as suggested, but that throws an error of:

```
Deep recursion on subroutine "Net::MQTT::Simple::_connect" at /usr/local/share/perl/5.30.0/Net/MQTT/Simple.pm line 190.
Deep recursion on subroutine "Net::MQTT::Simple::_send" at /usr/local/share/perl/5.30.0/Net/MQTT/Simple.pm line 226.
Deep recursion on subroutine "Net::MQTT::Simple::_send_subscribe" at /usr/local/share/perl/5.30.0/Net/MQTT/Simple.pm line 169.
Deep recursion on subroutine "Net::MQTT::Simple::_send" at /usr/local/share/perl/5.30.0/Net/MQTT/Simple.pm line 242.
```

After that, it doesn't seem like the connection establishes correctly.

**Comment by Juerd** [comment]
Juerd Waalboer skribis 2022-09-02 14:25 (+0200):
>    while (my $chunk = substr $data, 0, 16384, "") {
>        syswrite $socket, $data
>            or $self->_drop_connection;  # reconnect on next message
>    }

Oops, inside the loop it should be $chunk, not $data.

**Comment by CRCinAU** [comment]
Oh, of course hahaha... I didn't even pick that up :)

**Comment by CRCinAU** [comment]
The good news is that change seems to resolve sending things over 16Kb...

I'll do some more testing tomorrow - but I no longer get protocol errors etc when sending slightly higher resolution images.

**Comment by CRCinAU** [comment]
Further testing shows this is working well.....

```
Message received: 1662370167 - 32035 bytes
Message received: 1662370179 - 32042 bytes
Message received: 1662370191 - 32026 bytes
Message received: 1662370203 - 32074 bytes
Message received: 1662370214 - 32041 bytes
Message received: 1662370226 - 32016 bytes
Message received: 1662370238 - 32052 bytes
Message received: 1662370250 - 31954 bytes
Message received: 1662370261 - 31962 bytes
Message received: 1662370273 - 32037 bytes
Message received: 1662370285 - 31965 bytes
```

**Comment by CRCinAU** [comment]
Just as further testing, I tried with images ~80-90Kb today with no problems or protocol violations etc.

```
Message received: 1662433238 - 87654 bytes
Message received: 1662433254 - 87239 bytes
Message received: 1662433270 - 87111 bytes
Message received: 1662433286 - 86935 bytes
Message received: 1662433302 - 86813 bytes
Message received: 1662433317 - 86285 bytes
Message received: 1662433328 - 86929 bytes
Message received: 1662433339 - 86949 bytes
Message received: 1662433355 - 87063 bytes
Message received: 1662433370 - 87090 bytes
Message received: 1662433381 - 87089 bytes
Message received: 1662433392 - 85862 bytes
```

Is it possible to organise a new release to CPAN with this fixed? This would allow us to undo our hacky stuff to patch the module on building our app container.

**Comment by Juerd** [comment]
Thanks for testing. I'll probably process your PR and do a new release later this week.
