### ISSUE TITLE
Poor documentaion, possibly misleading?

### ISSUE THREAD

**Issue by gitcnd** [Juerd/Net-MQTT-Simple#24]
This isn't helpful: "Minimal MQTT version 3 interface"

Please explain exactly what this library actually IS.  I'm guessing it's only *half* of the interface, right?  Just the client only ?

Please remember that people using MQTT libs for the first time are not experts - you need to spell out what your code actually is for, not just skip all the boring" stuff that you obviously already know, because everyone else doesn't!!!!

Stick the word "client" in the title if that's what this really is, and maybe mention the purpose of the module somewhere (e.g. "so you can send data to remote MQTT servers")

Also. your link "full-featured [Net::MQTT](https://metacpan.org/pod/Net::MQTT)" leads to what looks like an antique almost entirely empty shell of an unfinished project with no examples or anything?  Is that the right thing?

**Comment by Juerd** [comment]
You have a point, but your tone is abusive and I would like to ask you to stop. I'm sharing my software with you, and in return you decide to bark instructions at me.

You're entirely free to avoid using my software if you don't like it.
