### ISSUE TITLE
last_will usage

### ISSUE THREAD

**Issue by christianTF** [Juerd/Net-MQTT-Simple#4]
Hi Juerd,

I'm trying to implement the last_will, but it seems that I do it not as I should.

My code is (simplified):
``` perl
my $gw_topicbase = "mqttgateway/";
my $mqtt = Net::MQTT::Simple::Auth->new($cfg->{Main}{brokeraddress}, $cfg_cred->{Credentials}{brokeruser}, $cfg_cred->{Credentials}{brokerpass});
$mqtt->last_will($gw_topicbase . "status", "Disconnected", 1);
$mqtt->retain($gw_topicbase . "status", "Connected");
```
It does not throw an error, but killing the process, no LWT is published by the broker.
You've written, that LWT cannot be changed for an open connection - is this the case for my new connection?

Thanks,
Christian

PS: I use `Net::MQTT::Simple::Auth` that extends the module with authentication.

**Comment by christianTF** [comment]
Ok, I identified, that the Auth overwrites the _send_connect to send the credentials:
https://github.com/christianTF/LoxBerry-Plugin-MQTT-Gateway/blob/4fcdac197756b702a8d3d7f2b240bc437645df26/bin/libs/Net/MQTT/Simple/Auth.pm#L19

You seem to be more affine in the MQTT protocol - do you know how the connection needs to be established, supporting both credentials and LWT?

Christian

**Comment by Juerd** [comment]
Meh, I guess I'll have to implement authentication. Would you be willing to beta test that? I don't feel like setting up a server with authentication just to test this...

**Comment by christianTF** [comment]
Yes, I have the Mosquitto infrastructure for that!

**Comment by Juerd** [comment]
Get it from the auth branch: https://github.com/Juerd/Net-MQTT-Simple/tree/auth

Note that the API is different from Net::MQTT::Simple::Auth. Instead of passing the values to `new`, you have to call `login` after `new`. If you need to use insecure connections, set `$ENV{MQTT_SIMPLE_ALLOW_INSECURE_LOGIN}`

**Comment by christianTF** [comment]
:satisfied: Works like a charm :satisfied:


Tested use-cases:

- LWT -> OK
- Anonymous -> OK
- With Credentials -> OK

https://github.com/christianTF/LoxBerry-Plugin-MQTT-Gateway/blob/f1cc90ed396c676f00548851d02079136cfb172b/bin/mqttgateway.pl#L367

Thanks a lot for the quick support!!
Christian
