### ISSUE TITLE
publish() stops working after unsubscribe()

### ISSUE THREAD

**Issue by qorron** [Juerd/Net-MQTT-Simple#9]
seen in 1.24

here is a small script to reproduce the behavior:
```
#!/usr/bin/perl
use strict;
use warnings;
use 5.020;
use Data::Dumper;

use Net::MQTT::Simple;
say 'connect'; 
my $mqtt = Net::MQTT::Simple->new("127.0.0.1");

$mqtt->subscribe(
    "topic/here" => sub {
        my ($topic, $message) = @_;
        print "[$topic] $message done\n";
                $mqtt->{stop_loop} = 1;
    },
); 
say 'publish'; 
$mqtt->publish("topic/here" => "gets published");
 
say 'run'; 
$mqtt->run(
);
$mqtt->unsubscribe("topic/here");
say 'publish after run'; 
$mqtt->publish("topic/here" => "never gets published");
```

it works without the unsubscribe line.
it also worked on older version and before the issue with mosquitto 1.6.1

in unsubscribe, I found:
```
    # Hardcoded "packet identifier" \0\0 for now.
    $self->_send("\xa2" . _prepend_variable_length("\0\0" .
        pack("(n/a*)*", @topics)
    ));
```

after changing this to `"\0\x01"`, it worked.
I don't know if this is to spec or breaks something else.

**Comment by Juerd** [comment]
> $mqtt->unsubscribe("topic/here");
> it works without the unsubscribe line.

You might be the first user to ever actually use `unsubscribe` ;)

Thanks for reporting the bug; will apply your suggested workaround soon.

> after changing this to `"\0\x01"`, it worked.
> I don't know if this is to spec or breaks something else.

It's actually Net::MQTT::Simple that breaks the spec. I misread the part
about packet identifiers and then only fixed it in _send_subscribe, not
in _send_unsubscribe.

Proven once again: copy/paste programming is dangerous, even if it's a
single line. And unit tests would have been a good idea too...

**Comment by qorron** [comment]
I like to keep things clean and I rely quite heavily on mqtt with all the tasmota devices in my home.
I do a lot of "issue command, read response" stuff and I know this isn't what mqtt was designed for but it is still the least painful way to keep everything updated and configured.

Thank you for maintaining the module! without it, my life would have been much harder.
